### ISSUE TITLE
Prefs command broken

### ISSUE THREAD

**Issue by wahfl2** [PITR-DEV/ukbutt-mod#13]
Running `ukbutt prefs` in the console shows the following error:

![image](https://github.com/PITR-DEV/ukbutt-mod/assets/59855656/c3cb3b80-03b8-4425-94a6-9f180003b923)
(I apologize, I'm not sure how to copy and paste from the console or if there's a log)

The mod seems to work fine, and setting `ukbutt.` preferences in LocalPrefs also seems to work.

**Comment by LobotomyCore** [comment]
I'm getting this too

**Comment by qdot** [comment]
@PITR-DEV We're getting quite a few reports about this on my discord now. Can we get an update patch if you've got time?
